version: '3'

volumes:
  portainer-data:

networks:
  net:

services:

  portainer:
    image: portainer/portainer:1.15.3
    networks:
      - net
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure

  swarmvisualizer:
    image: dockersamples/visualizer
    networks:
      - net
    ports:
      - 8081:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: replicated
      replicas: 4
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure